### PR TITLE
Merge pull request #1 from AY1920S1-CS2103T-F14-2/master

### PR DESCRIPTION
**Pull request by kerwin97**
testing merging own back into team to check if any difference, after merging team into own

### CODE REVIEW

**Comment by ngswbryan** [comment]
Good job on resolving your problems. Please make sure all files are checked.

**Comment by TeoShyanJie** [comment]
Nicely done, i am glad that you have successfully merged it. Perhaps you could check if your local files can work.

**Comment by caesarpjz** [comment]
Great Job!

**Comment by Xuerneas** [comment]
great job

**Pull request closed without merging**
